apiVersion: v1
kind: Service
metadata:
  name: spark-connect-server
spec:
  type: NodePort
  selector:
    app: spark-connect-server
  ports:
    - protocol: TCP
      port: 15002
      targetPort: 15002
      nodePort: 15002