apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-connect-server
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark-connect-server
  mainApplicationFile: local:///opt/spark-connect-server.py
  sparkVersion: "3.5.5"
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
  sparkConf:
    "spark.connect.enable": "true"
    "spark.connect.port": "15002"